<?xml version="1.0"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->
<definitions name="OdeSmx"
        targetNamespace="urn:/OdeSmx.wsdl"
        xmlns:tns="urn:/OdeSmx.wsdl"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
        xmlns="http://schemas.xmlsoap.org/wsdl/">

    <types>
        <schema targetNamespace="urn:/OdeSmx.wsdl"
                xmlns="http://www.w3.org/2000/10/XMLSchema">
                <element name="OdeSmxRequest" type="string"/>
                <element name="OdeSmxResponse" type="string"/>
        </schema>
    </types>

    <message name="OdeSmxRequest">
        <part name="parameters" element="tns:OdeSmxRequest"/>
    </message>

    <message name="OdeSmxResponse">
        <part name="parameters" element="tns:OdeSmxResponse"/>
    </message>

    <portType name="OdeSmxPortType">
        <operation name="OdeSmx">
            <input message="tns:OdeSmxRequest"/>
            <output message="tns:OdeSmxResponse"/>
        </operation>
    </portType>

    <plnk:partnerLinkType name="OdeSmxPartnerLinkType">
        <plnk:role name="Provider" portType="tns:OdeSmxPortType"/>
    </plnk:partnerLinkType>
    
    <!--
    
    This is an abstract interface/portType definition.  Note the lack of 
    binding and service: these are defined by the HTTP binding component.
    See OdeSmx-http/OdeSmx.wsdl for details.
    
    -->

</definitions>
